## Numpy

In [2]:
import numpy as np

In [3]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
two_d = np.array([range(i,i+3) for i in [2,4,6]])

In [6]:
two_d[1:,1:]

array([[5, 6],
       [7, 8]])

In [11]:
two_d[1:,0:2]

array([[4, 5],
       [6, 7]])

In [14]:
two_d[0:2,1:]

array([[3, 4],
       [5, 6]])

In [16]:
two_dx2 = two_d * 2
two_dx2

array([[ 4,  6,  8],
       [ 8, 10, 12],
       [12, 14, 16]])

In [17]:
np.concatenate((two_d, two_dx2))

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 4,  6,  8],
       [ 8, 10, 12],
       [12, 14, 16]])

In [18]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
my_ndarray = np.array([[2,3,4],[5,7,12],[10,1,3],[7,2,5]])

In [21]:
my_ndarray

array([[ 2,  3,  4],
       [ 5,  7, 12],
       [10,  1,  3],
       [ 7,  2,  5]])

In [22]:
my_ndarray.T

array([[ 2,  5, 10,  7],
       [ 3,  7,  1,  2],
       [ 4, 12,  3,  5]])

In [23]:
x = np.arange(1,6)
print(x)
np.add.reduce(x)

[1 2 3 4 5]

np.int64(15)

In [24]:
np.min(my_ndarray)
np.max(my_ndarray)
np.sum(my_ndarray)
np.multiply.reduce(x)
my_ndarray.sum()
np.multiply.reduce(my_ndarray)

array([700,  42, 720])

## Computation on arrays

In [25]:
my_ndarray_t = my_ndarray.T
my_ndarray_t

array([[ 2,  5, 10,  7],
       [ 3,  7,  1,  2],
       [ 4, 12,  3,  5]])

In [26]:
my_ndarray * my_ndarray

array([[  4,   9,  16],
       [ 25,  49, 144],
       [100,   1,   9],
       [ 49,   4,  25]])

## Dog Product

In [27]:
new_ar = np.random.random((3,3))
new_ar.dot(my_ndarray.T)
new_ar.shape
my_ndarray.shape

(4, 3)

In [4]:
import numpy as nu
nu.array([range(i,i+3) for i in [0,3,6]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
matrix = np.arange(9).reshape(3,3)

In [6]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
# replace all odd numbers with -1
arr = np.array([1,2,3,4,5,6,7,8,9,10,11])
arr[0:11:2]=-1
#arr[arr % 2 != 0]
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1])

In [21]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11])
arr[arr > 7]
# or arr[7:11:1]

array([ 8,  9, 10, 11])

## PANDAS

In [12]:
import pandas as pd

In [13]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])

In [14]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [22]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [23]:
data[:2]

0    0.25
1    0.50
dtype: float64

In [24]:
data = pd.Series({2: 'a', 3: 'b', 4: 'c'})

In [25]:
data

2    a
3    b
4    c
dtype: object

## Creating a pandas dataframe

In [56]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Kenneth', 'Sandra'],
    'Age': [24, 28, 22, 35, np.nan],
    'City': ['Edo', 'Ibadan', 'Warri', 'Edo', np.nan]
}
data = pd.DataFrame(data)
data

      Name   Age    City
0    Alice  24.0     Edo
1      Bob  28.0  Ibadan
2  Charlie  22.0   Warri
3  Kenneth  35.0     Edo
4   Sandra   NaN     NaN

In [39]:
data[(data['Age'] > 22) & (data['City'] == 'Edo')]

      Name  Age City
0    Alice   24  Edo
3  Kenneth   35  Edo

In [42]:
data['Age'].sum()

np.int64(109)

In [43]:
data['Age'].mean()

np.float64(27.25)

In [57]:
data['Math Score'] = [70,32,58,81,60]

data

      Name   Age    City  Math Score
0    Alice  24.0     Edo          70
1      Bob  28.0  Ibadan          32
2  Charlie  22.0   Warri          58
3  Kenneth  35.0     Edo          81
4   Sandra   NaN     NaN          54

In [59]:
data['English Score'] = [85, 81, 73, 92, 70]
data['score'] = (data['Math Score'] + data['English Score']) / 2
data

      Name   Age    City  Math Score  English Score  score
0    Alice  24.0     Edo          70             85   77.5
1      Bob  28.0  Ibadan          32             81   56.5
2  Charlie  22.0   Warri          58             73   65.5
3  Kenneth  35.0     Edo          81             92   86.5
4   Sandra   NaN     NaN          54             70   62.0

In [60]:
len(data['City'])

5

### Data Cleaning

In [62]:
mean_age = data['Age'].mean()
data['Age'] = data['Age'].fillna(mean_age)
data

      Name    Age    City  Math Score  English Score  score
0    Alice  24.00     Edo          70             85   77.5
1      Bob  28.00  Ibadan          32             81   56.5
2  Charlie  22.00   Warri          58             73   65.5
3  Kenneth  35.00     Edo          81             92   86.5
4   Sandra  27.25     NaN          54             70   62.0

In [68]:
new_city = 'Lagos'
data['City'] = data['City'].fillna(new_city)
data

      Name    Age    City  Math Score  English Score  score
0    Alice  24.00     Edo          70             85   77.5
1      Bob  28.00  Ibadan          32             81   56.5
2  Charlie  22.00   Warri          58             73   65.5
3  Kenneth  35.00     Edo          81             92   86.5
4   Sandra  27.25   Lagos          54             70   62.0

In [ ]:
data.iloc[0,5] = 67
df.iloc[0:5, 3:5] + 10