## Numpy

In [1]:
import numpy as np

In [2]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [3]:
two_d = np.array([range(i,i+3) for i in [2,4,6]])

In [4]:
two_d[1:,1:]

array([[5, 6],
       [7, 8]])

In [5]:
two_d[1:,0:2]

array([[4, 5],
       [6, 7]])

In [6]:
two_d[0:2,1:]

array([[3, 4],
       [5, 6]])

In [7]:
two_dx2 = two_d * 2
two_dx2

array([[ 4,  6,  8],
       [ 8, 10, 12],
       [12, 14, 16]])

In [8]:
np.concatenate((two_d, two_dx2))

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 4,  6,  8],
       [ 8, 10, 12],
       [12, 14, 16]])

In [9]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
my_ndarray = np.array([[2,3,4],[5,7,12],[10,1,3],[7,2,5]])

In [11]:
my_ndarray

array([[ 2,  3,  4],
       [ 5,  7, 12],
       [10,  1,  3],
       [ 7,  2,  5]])

In [12]:
my_ndarray.T

array([[ 2,  5, 10,  7],
       [ 3,  7,  1,  2],
       [ 4, 12,  3,  5]])

In [13]:
x = np.arange(1,6)
print(x)
np.add.reduce(x)

[1 2 3 4 5]

np.int64(15)

In [14]:
np.min(my_ndarray)
np.max(my_ndarray)
np.sum(my_ndarray)
np.multiply.reduce(x)
my_ndarray.sum()
np.multiply.reduce(my_ndarray)

array([700,  42, 720])

## Computation on arrays

In [15]:
my_ndarray_t = my_ndarray.T
my_ndarray_t

array([[ 2,  5, 10,  7],
       [ 3,  7,  1,  2],
       [ 4, 12,  3,  5]])

In [16]:
my_ndarray * my_ndarray

array([[  4,   9,  16],
       [ 25,  49, 144],
       [100,   1,   9],
       [ 49,   4,  25]])

## Dog Product

In [17]:
new_ar = np.random.random((3,3))
new_ar.dot(my_ndarray.T)
new_ar.shape
my_ndarray.shape

(4, 3)

In [18]:
import numpy as nu
nu.array([range(i,i+3) for i in [0,3,6]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
matrix = np.arange(9).reshape(3,3)

In [20]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
# replace all odd numbers with -1
arr = np.array([1,2,3,4,5,6,7,8,9,10,11])
arr[0:11:2]=-1
#arr[arr % 2 != 0]
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1])

In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11])
arr[arr > 7]
# or arr[7:11:1]

array([ 8,  9, 10, 11])

## PANDAS

In [23]:
import pandas as pd

In [24]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])

In [25]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [26]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [27]:
data[:2]

0    0.25
1    0.50
dtype: float64

In [28]:
data = pd.Series({2: 'a', 3: 'b', 4: 'c'})

In [29]:
data

2    a
3    b
4    c
dtype: object

## Creating a pandas dataframe

In [30]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Kenneth', 'Sandra'],
    'Age': [24, 28, 22, 35, np.nan],
    'City': ['Edo', 'Ibadan', 'Warri', 'Edo', np.nan]
}
data = pd.DataFrame(data)
data

      Name   Age    City
0    Alice  24.0     Edo
1      Bob  28.0  Ibadan
2  Charlie  22.0   Warri
3  Kenneth  35.0     Edo
4   Sandra   NaN     NaN

In [31]:
data[(data['Age'] > 22) & (data['City'] == 'Edo')]

      Name   Age City
0    Alice  24.0  Edo
3  Kenneth  35.0  Edo

In [32]:
data['Age'].sum()

np.float64(109.0)

In [33]:
data['Age'].mean()

np.float64(27.25)

In [34]:
data['Math Score'] = [70,32,58,81,60]

data

      Name   Age    City  Math Score
0    Alice  24.0     Edo          70
1      Bob  28.0  Ibadan          32
2  Charlie  22.0   Warri          58
3  Kenneth  35.0     Edo          81
4   Sandra   NaN     NaN          60

In [35]:
data['English Score'] = [85, 81, 73, 92, 70]
data['score'] = (data['Math Score'] + data['English Score']) / 2
data

      Name   Age    City  Math Score  English Score  score
0    Alice  24.0     Edo          70             85   77.5
1      Bob  28.0  Ibadan          32             81   56.5
2  Charlie  22.0   Warri          58             73   65.5
3  Kenneth  35.0     Edo          81             92   86.5
4   Sandra   NaN     NaN          60             70   65.0

In [36]:
len(data['City'])

5

### Data Cleaning

In [37]:
mean_age = data['Age'].mean()
data['Age'] = data['Age'].fillna(mean_age)
data

      Name    Age    City  Math Score  English Score  score
0    Alice  24.00     Edo          70             85   77.5
1      Bob  28.00  Ibadan          32             81   56.5
2  Charlie  22.00   Warri          58             73   65.5
3  Kenneth  35.00     Edo          81             92   86.5
4   Sandra  27.25     NaN          60             70   65.0

In [38]:
new_city = 'Lagos'
data['City'] = data['City'].fillna(new_city)
data

      Name    Age    City  Math Score  English Score  score
0    Alice  24.00     Edo          70             85   77.5
1      Bob  28.00  Ibadan          32             81   56.5
2  Charlie  22.00   Warri          58             73   65.5
3  Kenneth  35.00     Edo          81             92   86.5
4   Sandra  27.25   Lagos          60             70   65.0

In [39]:
data.iloc[0,5] = 67
data.iloc[0:5, 3:5] + 10

   Math Score  English Score
0          80             95
1          42             91
2          68             83
3          91            102
4          70             80

In [40]:
data

      Name    Age    City  Math Score  English Score  score
0    Alice  24.00     Edo          70             85   67.0
1      Bob  28.00  Ibadan          32             81   56.5
2  Charlie  22.00   Warri          58             73   65.5
3  Kenneth  35.00     Edo          81             92   86.5
4   Sandra  27.25   Lagos          60             70   65.0

In [41]:
data = pd.Series([1, np.nan, 'hello', None])

In [42]:
data.isnull

<bound method Series.isnull of 0        1
1      NaN
2    hello
3     None
dtype: object>

In [43]:
data.dropna()

0        1
2    hello
dtype: object

In [44]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [45]:
df = pd.DataFrame([[1, np.nan, 2], [2,3,5], [np.nan, 4, 6]])
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [46]:
df[3]=9
df[4]= [5, np.nan, 6]
df

     0    1  2  3    4
0  1.0  NaN  2  9  5.0
1  2.0  3.0  5  9  NaN
2  NaN  4.0  6  9  6.0

In [47]:
df.dropna(axis=1)

   2  3
0  2  9
1  5  9
2  6  9

In [41]:
#df.dropna(inplace=True)

In [48]:
df.fillna(0)

     0    1  2  3    4
0  1.0  0.0  2  9  5.0
1  2.0  3.0  5  9  0.0
2  0.0  4.0  6  9  6.0

In [49]:
df

     0    1  2  3    4
0  1.0  NaN  2  9  5.0
1  2.0  3.0  5  9  NaN
2  NaN  4.0  6  9  6.0

In [50]:
df.ffill()

     0    1  2  3    4
0  1.0  NaN  2  9  5.0
1  2.0  3.0  5  9  5.0
2  2.0  4.0  6  9  6.0

In [6]:
!pip install torchvision

Collecting torchvision
  Downloading torchvision-0.27.0-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Requirement already satisfied: numpy in c:\users\clinton\anaconda3\lib\site-packages (from torchvision) (2.3.5)
Collecting torch==2.12.0 (from torchvision)
  Downloading torch-2.12.0-cp313-cp313-win_amd64.whl.metadata (31 kB)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\clinton\anaconda3\lib\site-packages (from torchvision) (12.0.0)
Requirement already satisfied: filelock in c:\users\clinton\anaconda3\lib\site-packages (from torch==2.12.0->torchvision) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\clinton\anaconda3\lib\site-packages (from torch==2.12.0->torchvision) (4.15.0)
Requirement already satisfied: setuptools<82 in c:\users\clinton\anaconda3\lib\site-packages (from torch==2.12.0->torchvision) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\clinton\anaconda3\lib\site-packages (from torch==2.12.0->torchvision) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\clinton\anaconda3\lib\site-packages (from torch==2.12.0->torchvision) (3.5)
Requirement already satisfied: jinja2 in c:\users\clinton\anaconda3\lib\site-packages (from torch==2.12.0->torchvision) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\clinton\anaconda3\lib\site-packages (from torch==2.12.0->torchvision) (2025.10.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\clinton\anaconda3\lib\site-packages (from sympy>=1.13.3->torch==2.12.0->torchvision) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\clinton\anaconda3\lib\site-packages (from jinja2->torch==2.12.0->torchvision) (3.0.2)
Downloading torchvision-0.27.0-cp313-cp313-win_amd64.whl (4.1 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.1 MB ? eta -:--:--
   ---------- ----------------------------- 1.0/4.1 MB 3.3 MB/s eta 0:00:01
   -------------------- ------------------- 2.1/4.1 MB 3.8 MB/s eta 0:00:01
   ---------------------------- ----------- 2.9/4.1 MB 3.9 MB/s eta 0:00:01
   -------------------------------------- - 3.9/4.1 MB 4.1 MB/s eta 0:00:01
   -------------------------------------- - 3.9/4.1 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 4.1/4.1 MB 3.3 MB/s  0:00:01
Downloading torch-2.12.0-cp313-cp313-win_amd64.whl (123.0 MB)
   ---------------------------------------- 0.0/123.0 MB ? eta -:--:--
   ---------------------------------------- 0.8/123.0 MB 5.2 MB/s eta 0:00:24
   ---------------------------------------- 1.3/123.0 MB 4.2 MB/s eta 0:00:29
    --------------------------------------- 2.4/123.0 MB 3.7 MB/s eta 0:00:33
    --------------------------------------- 2.9/123.0 MB 3.8 MB/s eta 0:00:32
    --------------------------------------- 2.9/123.0 MB 3.8 MB/s eta 0:00:32
   - -------------------------------------- 5.0/123.0 MB 3.9 MB/s eta 0:00:30
   - -------------------------------------- 5.5/123.0 MB 3.8 MB/s eta 0:00:32
   -- ------------------------------------- 6.3/123.0 MB 3.8 MB/s eta 0:00:31
   -- ------------------------------------- 7.3/123.0 MB 3.9 MB/s eta 0:00:30
   -- ------------------------------------- 8.1/123.0 MB 3.9 MB/s eta 0:00:30
   -- ------------------------------------- 8.9/123.0 MB 3.9 MB/s eta 0:00:30
   --- ------------------------------------ 9.4/123.0 MB 3.8 MB/s eta 0:00:31
   --- ------------------------------------ 9.7/123.0 MB 3.6 MB/s eta 0:00:32
   --- ------------------------------------ 10.5/123.0 MB 3.6 MB/s eta 0:00:32
   --- ------------------------------------ 11.0/123.0 MB 3.5 MB/s eta 0:00:33
   --- ------------------------------------ 12.1/123.0 MB 3.6 MB/s eta 0:00:32
   ---- ----------------------------------- 13.9/123.0 MB 3.9 MB/s eta 0:00:29
   ----- ---------------------------------- 15.5/123.0 MB 4.0 MB/s eta 0:00:27
   ----- ---------------------------------- 16.8/123.0 MB 4.2 MB/s eta 0:00:26
   ----- ---------------------------------- 18.1/123.0 MB 4.3 MB/s eta 0:00:25
   ------ --------------------------------- 19.9/123.0 MB 4.5 MB/s eta 0:00:23
   ------- -------------------------------- 21.8/123.0 MB 4.7 MB/s eta 0:00:22
   ------- -------------------------------- 23.3/123.0 MB 4.8 MB/s eta 0:00:21
   -------- ------------------------------- 25.4/123.0 MB 5.0 MB/s eta 0:00:20
   -------- ------------------------------- 27.0/123.0 MB 5.1 MB/s eta 0:00:19
   --------- ------------------------------ 28.3/123.0 MB 5.2 MB/s eta 0:00:19
   --------- ------------------------------ 29.4/123.0 MB 5.2 MB/s eta 0:00:19
   --------- ------------------------------ 30.7/123.0 MB 5.2 MB/s eta 0:00:18
   ---------- ----------------------------- 32.2/123.0 MB 5.2 MB/s eta 0:00:18
   ----------- ---------------------------- 34.1/123.0 MB 5.4 MB/s eta 0:00:17
   ----------- ---------------------------- 35.7/123.0 MB 5.4 MB/s eta 0:00:17
   ------------ --------------------------- 37.2/123.0 MB 5.5 MB/s eta 0:00:16
   ------------ --------------------------- 38.8/123.0 MB 5.6 MB/s eta 0:00:16
   ------------- -------------------------- 40.4/123.0 MB 5.6 MB/s eta 0:00:15
   ------------- -------------------------- 41.7/123.0 MB 5.6 MB/s eta 0:00:15
   ------------- -------------------------- 43.0/123.0 MB 5.7 MB/s eta 0:00:15
   -------------- ------------------------- 44.8/123.0 MB 5.7 MB/s eta 0:00:14
   --------------- ------------------------ 46.1/123.0 MB 5.7 MB/s eta 0:00:14
   --------------- ------------------------ 48.0/123.0 MB 5.8 MB/s eta 0:00:13
   ---------------- ----------------------- 49.5/123.0 MB 5.9 MB/s eta 0:00:13
   ---------------- ----------------------- 51.1/123.0 MB 5.9 MB/s eta 0:00:13
   ----------------- ---------------------- 52.7/123.0 MB 5.9 MB/s eta 0:00:12
   ----------------- ---------------------- 54.3/123.0 MB 6.0 MB/s eta 0:00:12
   ------------------ --------------------- 55.8/123.0 MB 6.0 MB/s eta 0:00:12
   ------------------ --------------------- 57.7/123.0 MB 6.1 MB/s eta 0:00:11
   ------------------- -------------------- 59.2/123.0 MB 6.1 MB/s eta 0:00:11
   ------------------- -------------------- 61.1/123.0 MB 6.1 MB/s eta 0:00:11
   -------------------- ------------------- 62.9/123.0 MB 6.2 MB/s eta 0:00:10
   -------------------- ------------------- 64.5/123.0 MB 6.2 MB/s eta 0:00:10
   --------------------- ------------------ 65.8/123.0 MB 6.2 MB/s eta 0:00:10
   --------------------- ------------------ 66.8/123.0 MB 6.2 MB/s eta 0:00:10
   ---------------------- ----------------- 67.9/123.0 MB 6.2 MB/s eta 0:00:09
   ---------------------- ----------------- 69.2/123.0 MB 6.2 MB/s eta 0:00:09
   ---------------------- ----------------- 70.5/123.0 MB 6.2 MB/s eta 0:00:09
   ----------------------- ---------------- 71.8/123.0 MB 6.2 MB/s eta 0:00:09
   ----------------------- ---------------- 73.1/123.0 MB 6.2 MB/s eta 0:00:09
   ------------------------ --------------- 74.7/123.0 MB 6.2 MB/s eta 0:00:08
   ------------------------ --------------- 76.3/123.0 MB 6.2 MB/s eta 0:00:08
   ------------------------- -------------- 78.1/123.0 MB 6.2 MB/s eta 0:00:08
   -------------------------- ------------- 80.0/123.0 MB 6.3 MB/s eta 0:00:07
   -------------------------- ------------- 81.3/123.0 MB 6.3 MB/s eta 0:00:07
   -------------------------- ------------- 81.8/123.0 MB 6.2 MB/s eta 0:00:07
   -------------------------- ------------- 82.6/123.0 MB 6.2 MB/s eta 0:00:07
   --------------------------- ------------ 83.6/123.0 MB 6.2 MB/s eta 0:00:07
   --------------------------- ------------ 84.7/123.0 MB 6.1 MB/s eta 0:00:07
   --------------------------- ------------ 85.5/123.0 MB 6.1 MB/s eta 0:00:07
   ---------------------------- ----------- 86.2/123.0 MB 6.1 MB/s eta 0:00:07
   ---------------------------- ----------- 86.8/123.0 MB 6.0 MB/s eta 0:00:06
   ---------------------------- ----------- 87.8/123.0 MB 6.0 MB/s eta 0:00:06
   ---------------------------- ----------- 88.9/123.0 MB 6.0 MB/s eta 0:00:06
   ----------------------------- ---------- 90.2/123.0 MB 6.0 MB/s eta 0:00:06
   ----------------------------- ---------- 91.2/123.0 MB 6.0 MB/s eta 0:00:06
   ------------------------------ --------- 92.3/123.0 MB 6.0 MB/s eta 0:00:06
   ------------------------------ --------- 93.6/123.0 MB 6.0 MB/s eta 0:00:05
   ------------------------------ --------- 94.9/123.0 MB 6.0 MB/s eta 0:00:05
   ------------------------------- -------- 95.9/123.0 MB 6.0 MB/s eta 0:00:05
   ------------------------------- -------- 97.3/123.0 MB 6.0 MB/s eta 0:00:05
   -------------------------------- ------- 98.6/123.0 MB 6.0 MB/s eta 0:00:05
   -------------------------------- ------- 99.6/123.0 MB 6.0 MB/s eta 0:00:04
   -------------------------------- ------- 100.9/123.0 MB 6.0 MB/s eta 0:00:04
   --------------------------------- ------ 102.0/123.0 MB 6.0 MB/s eta 0:00:04
   --------------------------------- ------ 103.3/123.0 MB 5.9 MB/s eta 0:00:04
   --------------------------------- ------ 104.3/123.0 MB 5.9 MB/s eta 0:00:04
   ---------------------------------- ----- 105.6/123.0 MB 5.9 MB/s eta 0:00:03
   ---------------------------------- ----- 106.7/123.0 MB 5.9 MB/s eta 0:00:03
   ----------------------------------- ---- 107.7/123.0 MB 5.9 MB/s eta 0:00:03
   ----------------------------------- ---- 108.8/123.0 MB 5.9 MB/s eta 0:00:03
   ----------------------------------- ---- 109.6/123.0 MB 5.9 MB/s eta 0:00:03
   ----------------------------------- ---- 110.6/123.0 MB 5.9 MB/s eta 0:00:03
   ------------------------------------ --- 111.7/123.0 MB 5.9 MB/s eta 0:00:02
   ------------------------------------ --- 111.9/123.0 MB 5.9 MB/s eta 0:00:02
   ------------------------------------ --- 113.5/123.0 MB 5.9 MB/s eta 0:00:02
   ------------------------------------- -- 114.0/123.0 MB 5.8 MB/s eta 0:00:02
   ------------------------------------- -- 114.6/123.0 MB 5.8 MB/s eta 0:00:02
   ------------------------------------- -- 115.1/123.0 MB 5.7 MB/s eta 0:00:02
   ------------------------------------- -- 115.9/123.0 MB 5.7 MB/s eta 0:00:02
   ------------------------------------- -- 116.4/123.0 MB 5.7 MB/s eta 0:00:02
   -------------------------------------- - 117.2/123.0 MB 5.6 MB/s eta 0:00:02
   -------------------------------------- - 118.0/123.0 MB 5.6 MB/s eta 0:00:01
   -------------------------------------- - 118.8/123.0 MB 5.6 MB/s eta 0:00:01
   -------------------------------------- - 119.8/123.0 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  120.6/123.0 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  121.6/123.0 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  122.4/123.0 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  122.9/123.0 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------  122.9/123.0 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------  122.9/123.0 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------  122.9/123.0 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------- 123.0/123.0 MB 5.4 MB/s  0:00:22
Installing collected packages: torch, torchvision

   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]

In [7]:
from torchvision import models

In [4]:
def factorial(n):
    if n == 1:
        return 1
    return factorial(n-1)*n

factorial(5)

120

### Write a recursive function to find the nth fibonnacci number.

### Fibonnacci number: 0 1 1 2 3 5 8 13 21 34

### Input: 9
### Output: 21

In [24]:
#Fibonnacci_number= 0, 1, 1, 2, 3, 5, 8, 13, 21, 34
#Fibonnacci_number[0+4+1]

5

In [41]:
#Fibonnacci number: 0 1 1 2 3 5 8 13 21 34
def fibonacci_recursive(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci_recursive(n-1) + fibonacci_recursive(n-2)

print(fibonacci_recursive(3))

2